---
# tasks file for mysql
- name: install tools for python and mysql
  apt:  name={{item}} state=present update_cache=yes
  with_items:
    - python-mysqldb
    
- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes
  
- name: ensure mysql is listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address 
              line="bind-address = {{ ansible_eth2.ipv4.address }}"
  notify: restart mysql
  
- name: ensure mysql started
  service: name=mysql state=started enabled=yes     
  
- name: create demo database
  mysql_db: name=demo state=present
  
- name: create db user for demo
  mysql_user: name=demo password="{{ db_user_pass }}" priv=demo.*:ALL host='%' state=present
  
- name: create admin user for db user
  mysql_user: name=clint password="{{ db_admin_pass }}" priv=*.*:ALL host='%' state=present  