---
  - hosts: database
    become: true
    roles:
      - role: mysql
        db_user_name: "{{ db_user }}"
        db_user_pass: "{{ vault_db_pass }}"
        db_user_host: '%' 

        

        