---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: check nginx (load balancing) status
        command: service nginx status
        
      - name: verify nginx port is listening on 80
        wait_for: port=80 timeout=1
        
  - hosts: webserver
    become: true
    tasks:
      - name: check apache2 status
        command: service apache2 status

      - name: verify apache2 port is listening on 80
        wait_for: port=80 timeout=1

  - hosts: database
    become: true
    tasks:
      - name: check database (mysql)
        command: service mysql status
        
      - name: verify mysql port is listening on 3306
        wait_for: port=3306 timeout=1
        